name: Build

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  macOS:
    strategy:
      fail-fast: false
      matrix:
       macos-version:  ['latest']
       python-version: ['3.13']
       qt-version: ['6.10.*']
       configuration: ['debug']
    runs-on: macos-${{ matrix.macos-version }}
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ matrix.qt-version }}
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'
        archives: 'qtmultimedia qtmacextras qtbase qttools'

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: '${{ matrix.python-version }}'

    - name: Checkout PythonQt
      uses: actions/checkout@v6

    - name: Ccache
      uses: hendrikmuhs/ccache-action@v1.2.20
      with:
         key: ${{ runner.os }}-${{ matrix.qt-version }}
         evict-old-files: 'job'

    - name: Detect exact versions
      id : versions
      run : |
        set -eu
        PYTHON_VERSION_FULL=$(python --version 2>&1 | cut -f 2 -d ' ')
        PYTHON_VERSION_SHORT=$(cut -f 1,2 -d . <<< $PYTHON_VERSION_FULL)
        QT_VERSION_FULL=$($QT_ROOT_DIR/bin/qmake -query QT_VERSION)
        QT_VERSION_SHORT=$(cut -f 1,2 -d . <<< $QT_VERSION_FULL)
        MACOS_VERSION_FULL=$(sw_vers -productVersion)
        MACOS_VERSION_SHORT=$(cut -f 1,2 -d . <<< $MACOS_VERSION_FULL)

        echo "PYTHON_VERSION_FULL=$PYTHON_VERSION_FULL" | tee -a $GITHUB_OUTPUT
        echo "PYTHON_VERSION_SHORT=$PYTHON_VERSION_SHORT" | tee -a $GITHUB_OUTPUT
        echo "QT_VERSION_FULL=$QT_VERSION_FULL" | tee -a $GITHUB_OUTPUT
        echo "QT_VERSION_SHORT=$QT_VERSION_SHORT" | tee -a $GITHUB_OUTPUT
        echo "MACOS_VERSION_FULL=$MACOS_VERSION_FULL" | tee -a $GITHUB_OUTPUT
        echo "MACOS_VERSION_SHORT=$MACOS_VERSION_SHORT" | tee -a $GITHUB_OUTPUT

    - name: Build PythonQt (generator_only)
      run: |
        set -ue
        echo ======= SYSTEM INFO ========
        uname -a; gcc --version | head -n 1; qmake --version
        echo ============================
        qmake CONFIG+=ccache CONFIG+=${{ matrix.configuration }} CONFIG+=sanitizer CONFIG+=sanitize_undefined CONFIG+=sanitize_address \
          CONFIG+=generator_only \
          -r PythonQt.pro
        make -j $(nproc)

    - name: Generate Wrappers
      run: |
        UBSAN_OPTIONS="halt_on_error=1" ASAN_OPTIONS="detect_leaks=0:detect_stack_use_after_return=1:fast_unwind_on_malloc=0" \
        ./generator/pythonqt_generator \
          --output-directory=.

    - name: Build PythonQt (exclude_generator)
      run: |
        set -ue
        echo ======= SYSTEM INFO ========
        uname -a; gcc --version | head -n 1; python --version; qmake --version
        echo ============================
        PYTHON_VERSION_MAJOR=$(cut -d . -f1 <<< ${{ steps.versions.outputs.PYTHON_VERSION_SHORT }})
        for i in "python${{ steps.versions.outputs.PYTHON_VERSION_SHORT }}-embed" "python${{ steps.versions.outputs.PYTHON_VERSION_SHORT }}" \
                 "python${PYTHON_VERSION_MAJOR}-embed" "python${PYTHON_VERSION_MAJOR}"
        do if pkg-config --exists "$i"; then PYTHON_PKGCONFIG_NAME="$i"; break; fi; done
        qmake CONFIG+=ccache CONFIG+=${{ matrix.configuration }} CONFIG+=sanitizer CONFIG+=sanitize_undefined CONFIG+=sanitize_address \
          CONFIG+=exclude_generator \
          PYTHON_VERSION=${{ steps.versions.outputs.PYTHON_VERSION_SHORT }} \
          PYTHON_DIR="$pythonLocation" \
          PKGCONFIG+=$PYTHON_PKGCONFIG_NAME \
          -r PythonQt.pro
        make -j $(nproc)
        PYTHONDEVMODE=1 PYTHONASYNCIODEBUG=1 PYTHONWARNINGS=error PYTHONMALLOC=malloc_debug \
        UBSAN_OPTIONS="halt_on_error=1" ASAN_OPTIONS="detect_leaks=0:detect_stack_use_after_return=1:fast_unwind_on_malloc=0" \
          make check TESTARGS="-platform offscreen"

    - name: Upload Wrappers
      if: ${{ contains(matrix.configuration, 'release') }}
      uses: actions/upload-artifact@v5
      with:
        name: wrappers_macos${{ steps.versions.outputs.MACOS_VERSION_SHORT }}_qt${{ steps.versions.outputs.QT_VERSION_SHORT }}
        path: generated_cpp
        if-no-files-found: error
